### PR TITLE
first step for moving to TypeScript

### PR DESCRIPTION
**Pull request by MrSpoocy**
First step, try it and tell me what is wrong :)

 - Change folder structure
 - mqtt-config -> TypeScript
 - zigbee2mqtt-config -> TypeScript
 - types.ts (currently all types included, need to split for each node)
 - add devDependencies
 - add build command (copy the html, svg .. files)

### CODE REVIEW

**Comment by Andreas-Huber** [comment]
Can you add the dist folder to the .gitignore? 
And also add `npm install typescript --save-dev` to the project?

**Comment by Andreas-Huber** [comment]
Ah, and what I forgot to mention, of course, delete the dist folder from the commits :-)

I'm also wondering, why git detected the move for the .js files - but not for the .HTML files.
I don't think it there is anything wrong with those files, it just breaks the git history if you want to go back for some reason.
image

I'll test it a bit later.

**Comment by MrSpoocy** [comment]
image

**Comment by Andreas-Huber** [comment]
Ok, looks good. Let's merge it and continue in the typescript branch :-)

**Pull request merged**
