### PR TITLE
check for action

### PR DESCRIPTION
**Pull request by MrSpoocy**
Power status have no action

### CODE REVIEW

**Review by Andreas-Huber — APPROVED** [review]
Sry had no time earlier. Looks perfect to me.

**Comment by Andreas-Huber** [comment]
@Dirnei maybe it is time for a new release?

**Comment by Andreas-Huber** [comment]
@Dirnei I think it is time for a new release?

**Comment by Dirnei** [comment]
Yes absolutely. I will trigger a release later today

**Comment by Dirnei** [comment]
shit i closed it without merging

**Pull request merged**
